-- contract: table=settlement_customer_monthly
-- 月度聚合快照表（由 settlement_customer 回写）
CREATE TABLE IF NOT EXISTS `settlement_customer_monthly` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `region` VARCHAR(32) NOT NULL,
  `cp` VARCHAR(32) NOT NULL,
  `school_name` VARCHAR(128) NOT NULL,
  `service_month` CHAR(7) NOT NULL COMMENT 'YYYY-MM',
  `settlement_value` DOUBLE NOT NULL DEFAULT 0,
  `customer_fee` DOUBLE NULL,
  `customer_bill` DOUBLE NULL,
  `customer_fee_owner_id` BIGINT UNSIGNED NULL,
  `network_line_fee` DOUBLE NULL,
  `network_line_bill` DOUBLE NULL,
  `network_line_fee_owner_id` BIGINT UNSIGNED NULL,
  `node_deduction_fee` DOUBLE NULL,
  `node_deduction_bill` DOUBLE NULL,
  `node_deduction_fee_owner_id` BIGINT UNSIGNED NULL,
  `channel_rate` DOUBLE NULL,
  `channel_bill` DOUBLE NULL,
  `channel_owner_user_id` BIGINT UNSIGNED NULL,
  `recalculated` TINYINT(1) NOT NULL DEFAULT 0,
  `last_recalc_time` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_scm_region_cp_school_month` (`region`, `cp`, `school_name`, `service_month`),
  KEY `idx_scm_service_month` (`service_month`),
  KEY `idx_scm_region_cp` (`region`, `cp`),
  KEY `idx_scm_owner_customer` (`customer_fee_owner_id`),
  KEY `idx_scm_owner_network` (`network_line_fee_owner_id`),
  KEY `idx_scm_owner_node` (`node_deduction_fee_owner_id`),
  KEY `idx_scm_owner_channel` (`channel_owner_user_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='客户结算月度聚合快照';
